// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poszzufylzzjrrbdxmoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvc3p6dWZ5bHp6anJyYmR4bW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzAzMzIsImV4cCI6MjA2Njk0NjMzMn0.FLbpxcvIIY2sxdNe6upqemOa8_WpPzTUGAnhXJfOU6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});